### ISSUE TITLE
convert project to typescript

### ISSUE THREAD

**Issue by n-peugnet** [n-peugnet/image-map-creator#17]
Maybe one day...

**Comment by alexdresko** [comment]
Just wanted to let you know I've started on this effort today. Was looking for random javascript projects to convert to typescript and landed on this one. I'd say I've made some huge headway, but there's still a bit to do. 

One of the great things about converting a project to typescript is finding all of the bugs that javascript won't tell you about. There definitely are a few that you'll need to look at. I'm out of time to play with this today, but figured I'd go ahead and let you look around: https://github.com/n-peugnet/image-map-creator/compare/master...alexdresko:typescript-conversion

Feel free to let me know if you have any questions. Your JS is pretty good, so the conversion has been fun.

**Comment by n-peugnet** [comment]
Wow thank you so much ! I planned to do it one day but didn't have the courage to start. I didn't expect somebody to help me as you did.

Are you going to finish the full conversion and make a pull request ?

**Comment by alexdresko** [comment]
Well, I'm going to do as much as I can, but there are some design decisions that you'll likely need to make. Like I said, the TS compiler found some problems, and I don't know how you'd want to resolve them.

This is the first time I've run into this kind of github situation. I have a branch that I can't pr on my own. If I make a pr, are you able to pull that branch and make changes with me?

**Comment by alexdresko** [comment]
Ahhhh.. The answer to that last question is yes. Neat. I'll try to create the pr tomorrow. Would be helpful if you pulled the branch and ran the compiler just to see the current state. You'll likely see some of the problems I'm referring to.

Are you familiar with TS and/or VS Code?

**Comment by n-peugnet** [comment]
Are you referring to something like [this](https://help.github.com/articles/checking-out-pull-requests-locally/) ?

I am not used yet to pull requests either. But I definitely agree with you about running the compiler myself.

I've never used typescript but I know other strong typed langages with similar syntax. However I use VSCode everyday.

**Comment by alexdresko** [comment]
This: 

![image](https://user-images.githubusercontent.com/333022/49375454-4b330500-f6d2-11e8-9f3f-764633f3ead2.png)

I'm definitely not done, but I think it'd be a good idea if you pulled what I've done and familiarized yourself with the current state of things. Let's make sure your dev environment works against the branch and that you're able to see what still needs to be done. You might even decide to make some changes while you're in there. Perhaps I've done enough of the legwork that you'll be able to finish it on your own -- and that's fine. 

Given the nature of the conversion, we probably shouldn't both be editing files at the same time.  I'll wait until you give me the go-ahead or until you have questions. Once I create the PR, I'll help however I can to get you up and running.

**Comment by alexdresko** [comment]
Okay, I've created the PR. I'm guessing you can clone my repo now and push to my `typescript-conversion` branch? Let's figure this out.

**Comment by n-peugnet** [comment]
I pulled your branch and I started  to make some changes but it seems to be infinite haha

**Comment by alexdresko** [comment]
Meh... We'll work through it. I feel like it's at least 80% done, plus what you've done. If you need a break, push what you've done and I'll take another stab at it.
