### ISSUE TITLE
Constructor crashes if called after document ready

### ISSUE THREAD

**Issue by ChaseOxide** [n-peugnet/image-map-creator#30]
To reproduce:
Call `new imageMapCreator("div-1")` after document is ready (e.g. setTimeout 1000ms or by button click)

It will throw an Error
```
p5.image-map-creator.ts?c85a:138 Uncaught TypeError: Cannot read property 'createCanvas' of undefined
    at imageMapCreator.setup (p5.image-map-creator.ts?c85a:138)
    at p5.<anonymous> (p5.js:46215)
    at p5.<anonymous> (p5.js:46150)
    at new p5 (p5.js:46434)
    at new imageMapCreator (p5.image-map-creator.ts?c85a:113)
    at index.html:32
```

It is caused by p5 immediately calling p5.setup before `new p5()` constructor completes (if document has been loaded)

Additional information:

- p5 reference - https://github.com/processing/p5.js/blob/0.6.0/src/core/core.js#L551
- Using `image-map-creator@1.1.7`, `p5@0.6.0`

**Comment by n-peugnet** [comment]
Thanks for your report, I released the fix in [version 1.1.8](https://github.com/n-peugnet/image-map-creator/releases/tag/1.1.8).
