### ISSUE TITLE
After select “rectangle” Tool, click one point, it will create a "rectangle",  it is not good for user experience, could we refine to avoid one point "rectangle"? 

### ISSUE THREAD

**Issue by zhuhongyin** [n-peugnet/image-map-creator#32]
This is an example, click one point, it will create a "rectangle".
<area shape="poly" coords="2,0,2,0,2,0,2,0,2,0" nohref alt=""  />
Some times, Users do not know that they have created many invisible rectangles.

**Comment by n-peugnet** [comment]
Thank you for reporting this. It is now fixed in version 1.1.9
