### ISSUE TITLE
when clicked log map, the dArea has circular structures

### ISSUE THREAD

**Issue by zhuhongyin** [n-peugnet/image-map-creator#33]
![image](https://user-images.githubusercontent.com/16753818/101239131-078b8f80-3720-11eb-8054-315aa7b8b645.png)
one more question, What is this variable of "dArea" used for? Is it a required variable or optional？

**Comment by n-peugnet** [comment]
Yes. The `ImageMap` object references an `AreaDefault` object in `dArea` and the `AreaDefault` object references an `ImageMap` object in `iMap`.

`dArea` is a property of `ImageMap` that contains a `DefaultArea` object. A agree that this may not be the most beautiful solution, but this allows me to generalize some area stuffs later.

**Comment by zhuhongyin** [comment]
Thank you very much for your detailed answers

**Comment by zhuhongyin** [comment]
> this allows me to generalize some area stuffs later.

that is a smart design, it is great for now. 
so let me confirm, dArea and the AreaDefault is used to draw the enter transparent area, right?

![image](https://user-images.githubusercontent.com/16753818/101970608-52e4f700-3c66-11eb-8a75-185e64b90bec.png)

**Comment by n-peugnet** [comment]
Exactly.

P.S. sorry I linked you the french version of mdn doc
