### ISSUE TITLE
Is it possible to draw areas every equal units ?

### ISSUE THREAD

**Issue by dusteve** [n-peugnet/image-map-creator#41]
Is it possible to make some like five px units, so when drawing area selected pixels will be rounded to the nearest fives.
Just where is that function located ?
This is my first steps with .js , and sorry if it was silly question.
Thank you in advance.

**Comment by n-peugnet** [comment]
Do you mean something like a grid ?

It is not possible currently, and I didn't plan to add this option in the near future.
