### ISSUE TITLE
[issue] I've lost my "accent circonflex" on my title "bâtard" as I saved a JSON

### ISSUE THREAD

**Issue by vincent-peugnet** [n-peugnet/image-map-creator#9]
There is a big problem on my "bâtard" word, used in the title...

![issue](https://user-images.githubusercontent.com/33429034/48316731-dba48b00-e5e7-11e8-8a9e-2f83abfa9185.png)

**Comment by n-peugnet** [comment]
Thank you, save files are now saved in utf-8 encoding. You will have to convert the encoding of your save file to get your `accent circonflex` back

**Comment by vincent-peugnet** [comment]
MERCI LE BOSS <3
